---
title: "Comparing Income across Gender among New Coders"
author: "Erik Rauer & Audrey Le Meur"
date: "5/14/2021"
output:
  pdf_document: default
  html_document: default
abstract: "This is our Abstract"
bibliography: references.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction

Test [@larson_yitbarek_2017]
Again [@larson_2019]

# Method


# Data Analysis

```{r, include=FALSE}
library(broom)
library(dplyr)
library(knitr)
library(ggplot2)

actualData <- read.csv("ActualData.csv")

str(actualData)
```

## Comparing last year's earnings across gender

```{r, echo=FALSE, warning=FALSE}

plotData <- actualData %>%
  filter(!is.na(Gender))

#Income
ggplot(data=plotData, aes(x=Gender, y=Income)) + geom_boxplot() + labs(title="Figure 1: Last Year's Income by Gender", y="Income (US Dollars)") + theme(text=element_text(family="serif"), plot.title=element_text(hjust=0.5))

```
```{r, echo=FALSE, include=FALSE}

incomeFilter <- !is.na(actualData$Gender) & !is.na(actualData$Income)

aggregate(actualData$Income[incomeFilter], list(actualData$Gender[incomeFilter]), mean)

aggregate(actualData$Income[incomeFilter], list(actualData$Gender[incomeFilter]), median)

```
```{r, include=FALSE}
# Income
aovIncome <- aov(Income ~ Gender, data = actualData)

summary(aovIncome)

```
```{r, echo=FALSE}

incomeTukey <- tidy(TukeyHSD(aovIncome, "Gender", ordered=T))

incomeTukey <- incomeTukey %>%
  select(Comparison = contrast,
         Estimate = estimate,
         "Lower Bound" = conf.low,
         "Upper Bound" = conf.high,
         "P-Value" = adj.p.value)

kable(incomeTukey, caption="Tukey Results for Previous Year's Income by Gender")

```


## Comparing expected earnings across gender

```{r, echo=FALSE, warning=FALSE}

#Expected Earnings
ggplot(data=plotData, aes(x=Gender, y=ExpectedEarning)) + geom_boxplot() + labs(title="Figure 2: Expected Earnings by Gender", y="Expected Earnings (US Dollars)") + theme(text=element_text(family="serif"), plot.title=element_text(hjust=0.5))

```
```{r, echo=FALSE, include=FALSE}

expectedEarningFilter <- !is.na(actualData$Gender) & !is.na(actualData$ExpectedEarning)

aggregate(actualData$ExpectedEarning[expectedEarningFilter], list(actualData$Gender[expectedEarningFilter]), mean)

aggregate(actualData$ExpectedEarning[expectedEarningFilter], list(actualData$Gender[expectedEarningFilter]), median)
```
```{r, include=FALSE}

# Expected Income
aovExpected <- aov(ExpectedEarning ~ Gender, data = actualData)

summary(aovExpected)

```
```{r, echo=FALSE}

expectedTukey <- tidy(TukeyHSD(aovExpected, "Gender", ordered=T))

expectedTukey <- expectedTukey %>%
  select(Comparison = contrast,
         Estimate = estimate,
         "Lower Bound" = conf.low,
         "Upper Bound" = conf.high,
         "P-Value" = adj.p.value)

kable(expectedTukey, caption="Tukey Results for Expected Earnings by Gender")

```

## Comparing income and expected earnings on whether or not they attended a female coding event

```{r, echo=FALSE, warning=FALSE}

femaleEvents <- c("Ada", "Hackbright Academy", "Ladies Learning Code", "Grace Hopper", "Grace Hopper Academy", "Women Who Code", "Girl Develop It")

femaleEventData <- actualData %>%
  mutate(femaleEvent=(BootcampName %in% femaleEvents) | !is.na(CodeEventDjangoGirls) | !is.na(CodeEventGirlDev) | !is.na(CodeEventRailsGirls) | !is.na(CodeEventWomenCode)) %>% 
  filter(Gender == "female")

#Income
ggplot(data=femaleEventData, aes(x=femaleEvent, y=Income)) + geom_boxplot() + labs(title="Figure 3: Last Year's Income by Whether a Female Coding Event was Attended", y="Income (US Dollars)") + theme(text=element_text(family="serif"), plot.title=element_text(hjust=0.5))

#Expected Earnings
ggplot(data=femaleEventData, aes(x=femaleEvent, y=ExpectedEarning)) + geom_boxplot() + labs(title="Figure 3: Expected Earnings by Whether a Female Coding Event was Attended", y="Expected Earnings (US Dollars)") + theme(text=element_text(family="serif"), plot.title=element_text(hjust=0.5))

t.test(Income ~ femaleEvent, femaleEventData)

t.test(ExpectedEarning ~ femaleEvent, femaleEventData)

```


# Conclusion

# References